include: package:very_good_analysis/analysis_options.yaml
plugins:
  riverpod_lint: ^3.1.3
analyzer:
  plugins:
    lint_hard:
      diagnostics:
        document_thrown_exceptions: true
        unthrown_exceptions_documented: true
  errors:
    avoid_positional_boolean_parameters: ignore
    camel_case_types: ignore
    deprecated_member_use: ignore
    flutter_style_todos: ignore
    lines_longer_than_80_chars: ignore
    one_member_abstracts: ignore
    public_member_api_docs: ignore
    unnecessary_lambdas: ignore

  exclude:
    - "lib/generated"
