// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCofbPCfjFJwkMlGHav1c-szsUkqEL3wAw',
    appId: '1:802871659996:android:34c66160e6cebb96c11319',
    messagingSenderId: '802871659996',
    projectId: 'bulusalim-e8e7c',
    storageBucket: 'bulusalim-e8e7c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDiYYg7yWFBp4RiFwkPyNJs6dZA55yLafA',
    appId: '1:802871659996:ios:4944ee3f77885e1fc11319',
    messagingSenderId: '802871659996',
    projectId: 'bulusalim-e8e7c',
    storageBucket: 'bulusalim-e8e7c.firebasestorage.app',
    androidClientId: '802871659996-0uge5nb1c4b5jv7k432puheq836m0n2e.apps.googleusercontent.com',
    iosClientId: '802871659996-6fe630p3hiq3vd68lkjrefpsgpe18al1.apps.googleusercontent.com',
    iosBundleId: 'app.outnest',
  );

}