// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCofbPCfjFJwkMlGHav1c-szsUkqEL3wAw',
    appId: '1:802871659996:android:efc9c632ef59e1f9c11319',
    messagingSenderId: '802871659996',
    projectId: 'bulusalim-e8e7c',
    storageBucket: 'bulusalim-e8e7c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDiYYg7yWFBp4RiFwkPyNJs6dZA55yLafA',
    appId: '1:802871659996:ios:8cb30a7e27d760f7c11319',
    messagingSenderId: '802871659996',
    projectId: 'bulusalim-e8e7c',
    storageBucket: 'bulusalim-e8e7c.firebasestorage.app',
    iosBundleId: 'com.example.bulusalim',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDiYYg7yWFBp4RiFwkPyNJs6dZA55yLafA',
    appId: '1:802871659996:ios:8cb30a7e27d760f7c11319',
    messagingSenderId: '802871659996',
    projectId: 'bulusalim-e8e7c',
    authDomain: 'bulusalim-e8e7c.firebaseapp.com',
    storageBucket: 'bulusalim-e8e7c.firebasestorage.app',
  );
}
